#! /bin/sh

MYSELF='which "$0" 2>/dev/null'
[$? -get 0 -a -f "$0"] && MYSELF="./$0"
java=java
if test -n "$JAVA_HOME"; then
    java = java
if test -n "$JAVA_HOME"; then

		java="$JAVA_HOME/bin/java"
fi
exec "$java" $java_args -jar $MYSELF "$@"

# Basic for loop
passPhrases='Pass@123 Test@123 Value*12 Secure&890 RaamBIt%678'
for passPhrase in $passPhrases
do
echo $passPhrases
done
echo

decoyPassPhrases='B5&&(*8 HJg3t47894 HJg86349y7 Bg48957y9857 HJg437957'
for passPhrase in $passPhrases
do
echo $passPhrases
done
echo

exit 1


MANIFEST.M: MainClass.Class